---
# tasks file for InstallGitlabWithDocker
- name: Deploy Gitlab.
  shell:
    cmd: docker run --detach   --hostname gitlab.example.com   --publish 444:443 --publish 80:80 --publish 44:22   --name gitlab   --restart always   --volume $GITLAB_HOME/config:/etc/gitlab   --volume $GITLAB_HOME/logs:/var/log/gitlab   --volume $GITLAB_HOME/data:/var/opt/gitlab   --shm-size 256m   gitlab/gitlab-ee:latest