---
# tasks file for InstallRabbitMQ
- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest

- name: Install packages
  apt:
    name:
      - gnupg2
      - apt-transport-https
      - curl
      - wget
      - ca-certificates
      - software-properties-common
      - lsb-release 
    state: latest
    update_cache: true

- name: Team RabbitMQ's main signing key.
  ansible.builtin.shell:
    cmd: curl -1sLf "https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA" | sudo gpg --dearmor | sudo tee /usr/share/keyrings/com.rabbitmq.team.gpg > /dev/null

- name: Launchpad PPA that provides modern Erlang releases.
  ansible.builtin.shell:
    cmd: curl -1sLf "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xf77f1eda57ebb1cc" | sudo gpg --dearmor | sudo tee /usr/share/keyrings/net.launchpad.ppa.rabbitmq.erlang.gpg > /dev/null

- name: PackageCloud RabbitMQ repository.
  ansible.builtin.shell:
    cmd: curl -1sLf "https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey" | sudo gpg --dearmor | sudo tee /usr/share/keyrings/io.packagecloud.rabbitmq.gpg > /dev/null

- name: Add apt repositories maintained by Team RabbitMQ.
  ansible.builtin.shell:
    cmd: | 
         sudo tee /etc/apt/sources.list.d/rabbitmq.list <<EOF
          ## Provides modern Erlang/OTP releases
          ##
          ## "bionic" as distribution name should work for any reasonably recent Ubuntu or Debian release.
          ## See the release to distribution mapping table in RabbitMQ doc guides to learn more.
          deb [signed-by=/usr/share/keyrings/net.launchpad.ppa.rabbitmq.erlang.gpg] http://ppa.launchpad.net/rabbitmq/rabbitmq-erlang/ubuntu bionic main
          deb-src [signed-by=/usr/share/keyrings/net.launchpad.ppa.rabbitmq.erlang.gpg] http://ppa.launchpad.net/rabbitmq/rabbitmq-erlang/ubuntu bionic main

          ## Provides RabbitMQ
          ##
          ## "bionic" as distribution name should work for any reasonably recent Ubuntu or Debian release.
          ## See the release to distribution mapping table in RabbitMQ doc guides to learn more.
          deb [signed-by=/usr/share/keyrings/io.packagecloud.rabbitmq.gpg] https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu/ bionic main
          deb-src [signed-by=/usr/share/keyrings/io.packagecloud.rabbitmq.gpg] https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu/ bionic main

- name: Update package indices.
  apt:
    name: "*"
    state: latest

- name: Install Erlang packages.
  apt:
    name:
      - erlang-base
      - erlang-asn1 
      - erlang-crypto 
      - erlang-eldap 
      - erlang-ftp 
      - erlang-inets
      - erlang-mnesia 
      - erlang-os-mon 
      - erlang-parsetools 
      - erlang-public-key
      - erlang-runtime-tools 
      - erlang-snmp 
      - erlang-ssl
      - erlang-syntax-tools 
      - erlang-tftp 
      - erlang-tools 
      - erlang-xmerl
    state: latest
    update_cache: true

- name: Install rabbitmq-server and its dependencies.
  apt:
    name:
      - rabbitmq-server
    state: latest
    update_cache: true

- name: Setup RabbitMQ nodes & Define Erlang cookie.
  shell:
    cmd: |
          sudo systemctl stop rabbitmq-server
          echo "JFKZVCBYEISEQILVZMSD" | sudo tee /var/lib/rabbitmq/.erlang.cookie
          sudo systemctl start rabbitmq-server

- name: Enable management plugin.
  shell:
    cmd: rabbitmq-plugins enable rabbitmq_management